version: "3.8"

services:
  webserver:
    build: .
    container_name: webs
    networks:
      - mynet
    volumes:
      - myvol:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: mydb
    networks:
      - mynet
    volumes:
      - myvol_db:/var/lib/mysql

networks:
  mynet:


volumes:
  myvol:
  myvol_db:
